# Generated by Django 5.0.6 on 2024-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
