# Generated by Django 5.0.6 on 2024-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Voice', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='prueba'),
            preserve_default=False,
        ),
    ]
